// ---------- Data ----------
// Each row: id, label, and 5 slots [kana, romaji, ...alternate spellings] (null = empty slot)
export const ROWS = [
  { id: "a",  label: "a",  chars: [["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"]] },
  { id: "ka", label: "ka", chars: [["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"]] },
  { id: "sa", label: "sa", chars: [["さ","sa"],["し","shi","si"],["す","su"],["せ","se"],["そ","so"]] },
  { id: "ta", label: "ta", chars: [["た","ta"],["ち","chi","ti"],["つ","tsu","tu"],["て","te"],["と","to"]] },
  { id: "na", label: "na", chars: [["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"]] },
  { id: "ha", label: "ha", chars: [["は","ha"],["ひ","hi"],["ふ","fu","hu"],["へ","he"],["ほ","ho"]] },
  { id: "ma", label: "ma", chars: [["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"]] },
  { id: "ya", label: "ya", chars: [["や","ya"],null,["ゆ","yu"],null,["よ","yo"]] },
  { id: "ra", label: "ra", chars: [["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"]] },
  { id: "wa", label: "wa", chars: [["わ","wa"],null,null,null,["を","wo","o"]] },
  { id: "n",  label: "n",  chars: [["ん","n","nn"],null,null,null,null] },
];
export const DEFAULT_ROWS = ["a", "ka", "sa", "ta"];  // rows learned so far
export const MAX_BOX = 5;

export const ALL = ROWS.flatMap(r => r.chars.filter(Boolean).map(([kana, romaji, ...alts]) =>
  ({ kana, romaji, accepted: [romaji, ...alts], row: r.id })));

// Example words: [kana, romaji, kanji (or "" if usually written in kana), English, Chinese,
// pitch accent]. Pitch accent is the Tokyo-standard dictionary number: the mora after which
// the pitch drops (0 = flat, never drops).
// Only words spelled with basic hiragana (no ゛゜ or small kana). A word is shown only
// once every character in it belongs to the practice set, so the list grows with each row.
export const WORDS = [
  // あ か さ た rows only
  ["あい","ai","愛","love","爱",1],
  ["あお","ao","青","blue","蓝色",1],
  ["あか","aka","赤","red","红色",1],
  ["あき","aki","秋","autumn","秋天",1],
  ["あさ","asa","朝","morning","早上",1],
  ["あし","ashi","足","foot; leg","脚",2],
  ["あせ","ase","汗","sweat","汗",1],
  ["あそこ","asoko","","over there","那边",0],
  ["あたたかい","atatakai","暖かい","warm","温暖",4],
  ["あつい","atsui","暑い","hot (weather)","热",2],
  ["いえ","ie","家","house","房子",2],
  ["いけ","ike","池","pond","池塘",2],
  ["いく","iku","行く","to go","去",0],
  ["いし","ishi","石","stone","石头",2],
  ["いす","isu","椅子","chair","椅子",0],
  ["いたい","itai","痛い","painful; ouch!","疼",2],
  ["いち","ichi","一","one","一",2],
  ["いつ","itsu","","when","什么时候",1],
  ["いと","ito","糸","thread","线",1],
  ["うえ","ue","上","above; up","上面",0],
  ["うし","ushi","牛","cow","牛",0],
  ["うそ","uso","嘘","lie","谎言",1],
  ["うた","uta","歌","song","歌",2],
  ["うち","uchi","家","home","家",0],
  ["えき","eki","駅","station","车站",1],
  ["おいしい","oishii","美味しい","delicious","好吃",0],
  ["おおきい","ookii","大きい","big","大",3],
  ["おかし","okashi","お菓子","sweets; snacks","零食，点心",2],
  ["おと","oto","音","sound","声音",2],
  ["おとこ","otoko","男","man","男人",3],
  ["おととい","ototoi","一昨日","day before yesterday","前天",3],
  ["かお","kao","顔","face","脸",0],
  ["かき","kaki","柿","persimmon","柿子",0],
  ["かく","kaku","書く","to write","写",1],
  ["かさ","kasa","傘","umbrella","伞",1],
  ["かた","kata","肩","shoulder","肩膀",1],
  ["かたい","katai","固い","hard; firm","硬",0],
  ["かたち","katachi","形","shape","形状",0],
  ["きく","kiku","聞く","to listen; to ask","听；问",0],
  ["きせつ","kisetsu","季節","season","季节",1],
  ["きた","kita","北","north","北",0],
  ["くさ","kusa","草","grass","草",2],
  ["くち","kuchi","口","mouth","嘴",0],
  ["くつ","kutsu","靴","shoes","鞋子",2],
  ["けいたい","keitai","携帯","mobile phone","手机",0],
  ["けしき","keshiki","景色","scenery","风景",1],
  ["こえ","koe","声","voice","嗓音",1],
  ["ここ","koko","","here","这里",0],
  ["こし","koshi","腰","lower back; waist","腰",0],
  ["こたえ","kotae","答え","answer","答案",2],
  ["さか","saka","坂","slope","坡",2],
  ["さけ","sake","酒","alcohol; sake","酒",0],
  ["しお","shio","塩","salt","盐",2],
  ["しかく","shikaku","四角","square","四方形",0],
  ["した","shita","下","below; under","下面",0],
  ["すいか","suika","西瓜","watermelon","西瓜",0],
  ["すき","suki","好き","to like","喜欢",2],
  ["すし","sushi","寿司","sushi","寿司",2],
  ["せかい","sekai","世界","world","世界",1],
  ["せき","seki","席","seat","座位",1],
  ["そこ","soko","","there","那里",0],
  ["そと","soto","外","outside","外面",1],
  ["たいせつ","taisetsu","大切","important; precious","重要，珍贵",0],
  ["たかい","takai","高い","tall; expensive","高；贵",2],
  ["たこ","tako","蛸","octopus","章鱼",1],
  ["ちいさい","chiisai","小さい","small","小",3],
  ["ちかい","chikai","近い","near","近",2],
  ["ちかてつ","chikatetsu","地下鉄","subway","地铁",0],
  ["ちち","chichi","父","(my) father","父亲",1],
  ["つき","tsuki","月","moon","月亮",2],
  ["つくえ","tsukue","机","desk","书桌",0],
  ["て","te","手","hand","手",1],
  ["てき","teki","敵","enemy","敌人",0],
  ["てつ","tetsu","鉄","iron","铁",0],
  ["とおい","tooi","遠い","far","远",0],
  ["とけい","tokei","時計","clock; watch","钟表",0],
  ["とし","toshi","年","year; age","年；年龄",2],
  // unlock as more rows are added
  ["いぬ","inu","犬","dog","狗",2],
  ["ねこ","neko","猫","cat","猫",1],
  ["なつ","natsu","夏","summer","夏天",2],
  ["なに","nani","何","what","什么",1],
  ["おなか","onaka","お腹","stomach; belly","肚子",0],
  ["さかな","sakana","魚","fish","鱼",0],
  ["きのこ","kinoko","","mushroom","蘑菇",1],
  ["きつね","kitsune","狐","fox","狐狸",0],
  ["たぬき","tanuki","狸","raccoon dog","貉（狸猫）",1],
  ["はな","hana","花","flower","花",2],
  ["はし","hashi","箸","chopsticks","筷子",1],
  ["ひと","hito","人","person","人",0],
  ["ひこうき","hikouki","飛行機","airplane","飞机",2],
  ["ふね","fune","船","ship; boat","船",1],
  ["へそ","heso","臍","belly button","肚脐",0],
  ["ほし","hoshi","星","star","星星",0],
  ["め","me","目","eye","眼睛",1],
  ["みみ","mimi","耳","ear","耳朵",2],
  ["うみ","umi","海","sea","海",1],
  ["あめ","ame","雨","rain","雨",1],
  ["むし","mushi","虫","insect; bug","虫子",0],
  ["もも","momo","桃","peach","桃子",0],
  ["なまえ","namae","名前","name","名字",0],
  ["あたま","atama","頭","head","头",3],
  ["やま","yama","山","mountain","山",2],
  ["やさい","yasai","野菜","vegetable","蔬菜",0],
  ["へや","heya","部屋","room","房间",2],
  ["ゆき","yuki","雪","snow","雪",2],
  ["ふゆ","fuyu","冬","winter","冬天",2],
  ["よる","yoru","夜","night","夜晚",1],
  ["はる","haru","春","spring","春天",1],
  ["そら","sora","空","sky","天空",1],
  ["さくら","sakura","桜","cherry blossom","樱花",0],
  ["くるま","kuruma","車","car","汽车",0],
  ["くすり","kusuri","薬","medicine","药",0],
  ["とり","tori","鳥","bird","鸟",0],
  ["さる","saru","猿","monkey","猴子",1],
  ["こころ","kokoro","心","heart; mind","心",2],
  ["わたし","watashi","私","I; me","我",0],
  ["かわ","kawa","川","river","河",2],
  ["にわ","niwa","庭","garden","院子",0],
  ["ほん","hon","本","book","书",1],
  ["にほん","nihon","日本","Japan","日本",2],
  ["みかん","mikan","蜜柑","mandarin orange","橘子",1],
  ["てんき","tenki","天気","weather","天气",1],
  ["せんせい","sensei","先生","teacher","老师",3],
  ["おかあさん","okaasan","お母さん","mother","妈妈",2],
  ["こんにちは","konnichiwa","今日は","hello; good afternoon","你好",0],
  ["さようなら","sayounara","","goodbye","再见",4],
].map(([kana, romaji, kanji, en, zh, accent]) => ({ kana, romaji, kanji, en, zh, accent }));
