// Offline support: the app's own files are precached as one versioned set and served
// cache-first, so old and new files never mix. GitHub API calls are untouched.
// VERSION is generated by `npm run bump-sw` — rerun it whenever a listed file changes.
const VERSION = "1cc5edb7fbd8";
const CACHE = "hiragana-" + VERSION;
const FILES = [
  "./", "index.html", "css/style.css", "manifest.webmanifest",
  "js/app.js", "js/data.js", "js/store.js", "js/merge.js", "js/sync.js",
  "icons/icon-180.png", "icons/icon-192.png", "icons/icon-512.png",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: "reload" })))));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  e.respondWith(caches.open(CACHE).then(async cache => {
    const cached = await cache.match(e.request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(e.request);
    } catch (err) {
      if (e.request.mode === "navigate") {
        const shell = await cache.match("./");
        if (shell) return shell;
      }
      throw err;
    }
  }));
});
