// Offline support: the app's own files are precached as one versioned set and served
// cache-first, so old and new files never mix. GitHub API calls are untouched.
// VERSION is generated by `npm run bump-sw` — rerun it whenever a listed file changes.
const VERSION = "e9c8214368d0";
const CACHE = "hiragana-" + VERSION;
const FILES = [
  "./", "index.html", "css/style.css", "manifest.webmanifest",
  "js/app.js", "js/data.js", "js/store.js", "js/merge.js", "js/sync.js", "js/srs.js", "js/romaji.js", "js/cards.js",
  "js/decks/vocab.js", "js/decks/kanji.js", "js/decks/grammar.js",
  "icons/favicon-32.png", "icons/icon-180.png", "icons/icon-192.png", "icons/icon-512.png",
];

// Fetch each file past the CDN with a versioned query (so a stale edge copy cannot slip in),
// but store it under its plain path. Any failure rejects, so the install is all-or-nothing.
self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(cache => Promise.all(FILES.map(async f => {
    const res = await fetch(new Request(f + (f.includes("?") ? "&" : "?") + "v=" + VERSION, { cache: "reload" }));
    if (!res.ok) throw new Error(`precache failed for ${f}: ${res.status}`);
    await cache.put(f, res);
  }))));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  e.respondWith(caches.open(CACHE).then(async cache => {
    const cached = await cache.match(e.request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(e.request);
    } catch (err) {
      if (e.request.mode === "navigate") {
        const shell = await cache.match("./");
        if (shell) return shell;
      }
      throw err;
    }
  }));
});
