// Built-in kanji deck (JLPT N5). Entries are introduced in this order.
// on: on'yomi in katakana; kun: kun'yomi in hiragana ("." marks okurigana, "-" a suffix).
export const KANJI = [
  // ---- Numbers ----
  { kanji: "一", on: ["イチ", "イツ"], kun: ["ひと", "ひと.つ"], en: "one", zh: "一",
    words: [{ word: "一つ", kana: "ひとつ", en: "one (thing)", zh: "一个" },
            { word: "一月", kana: "いちがつ", en: "January", zh: "一月" },
            { word: "一人", kana: "ひとり", en: "one person; alone", zh: "一个人；独自" }] },
  { kanji: "二", on: ["ニ"], kun: ["ふた", "ふた.つ"], en: "two", zh: "二",
    words: [{ word: "二つ", kana: "ふたつ", en: "two (things)", zh: "两个" },
            { word: "二月", kana: "にがつ", en: "February", zh: "二月" },
            { word: "二人", kana: "ふたり", en: "two people", zh: "两个人" }] },
  { kanji: "三", on: ["サン"], kun: ["み", "みっ.つ"], en: "three", zh: "三",
    words: [{ word: "三つ", kana: "みっつ", en: "three (things)", zh: "三个" },
            { word: "三月", kana: "さんがつ", en: "March", zh: "三月" }] },
  { kanji: "四", on: ["シ"], kun: ["よ", "よん", "よっ.つ"], en: "four", zh: "四",
    words: [{ word: "四つ", kana: "よっつ", en: "four (things)", zh: "四个" },
            { word: "四月", kana: "しがつ", en: "April", zh: "四月" },
            { word: "四人", kana: "よにん", en: "four people", zh: "四个人" }] },
  { kanji: "五", on: ["ゴ"], kun: ["いつ", "いつ.つ"], en: "five", zh: "五",
    words: [{ word: "五つ", kana: "いつつ", en: "five (things)", zh: "五个" },
            { word: "五月", kana: "ごがつ", en: "May", zh: "五月" }] },
  { kanji: "六", on: ["ロク"], kun: ["む", "むっ.つ"], en: "six", zh: "六",
    words: [{ word: "六つ", kana: "むっつ", en: "six (things)", zh: "六个" },
            { word: "六月", kana: "ろくがつ", en: "June", zh: "六月" }] },
  { kanji: "七", on: ["シチ"], kun: ["なな", "なな.つ"], en: "seven", zh: "七",
    words: [{ word: "七つ", kana: "ななつ", en: "seven (things)", zh: "七个" },
            { word: "七月", kana: "しちがつ", en: "July", zh: "七月" }] },
  { kanji: "八", on: ["ハチ"], kun: ["や", "やっ.つ"], en: "eight", zh: "八",
    words: [{ word: "八つ", kana: "やっつ", en: "eight (things)", zh: "八个" },
            { word: "八月", kana: "はちがつ", en: "August", zh: "八月" }] },
  { kanji: "九", on: ["キュウ", "ク"], kun: ["ここの", "ここの.つ"], en: "nine", zh: "九",
    words: [{ word: "九つ", kana: "ここのつ", en: "nine (things)", zh: "九个" },
            { word: "九月", kana: "くがつ", en: "September", zh: "九月" }] },
  { kanji: "十", on: ["ジュウ"], kun: ["とお", "と"], en: "ten", zh: "十",
    words: [{ word: "十月", kana: "じゅうがつ", en: "October", zh: "十月" },
            { word: "十日", kana: "とおか", en: "the 10th (of the month); ten days", zh: "十号；十天" }] },
  { kanji: "百", on: ["ヒャク"], kun: [], en: "hundred", zh: "百",
    words: [{ word: "百円", kana: "ひゃくえん", en: "100 yen", zh: "一百日元" },
            { word: "三百", kana: "さんびゃく", en: "three hundred", zh: "三百" }] },
  { kanji: "千", on: ["セン"], kun: ["ち"], en: "thousand", zh: "千",
    words: [{ word: "千円", kana: "せんえん", en: "1,000 yen", zh: "一千日元" },
            { word: "三千", kana: "さんぜん", en: "three thousand", zh: "三千" }] },
  { kanji: "万", on: ["マン"], kun: [], en: "ten thousand", zh: "万",
    words: [{ word: "一万円", kana: "いちまんえん", en: "10,000 yen", zh: "一万日元" }] },
  { kanji: "円", on: ["エン"], kun: ["まる.い"], en: "yen; circle", zh: "日元；圆（日语中最常用作货币单位）",
    words: [{ word: "百円", kana: "ひゃくえん", en: "100 yen", zh: "一百日元" },
            { word: "円", kana: "えん", en: "yen", zh: "日元" }] },

  // ---- Days and elements ----
  { kanji: "日", on: ["ニチ", "ジツ"], kun: ["ひ", "-び", "-か"], en: "day; sun", zh: "日；太阳",
    words: [{ word: "日本", kana: "にほん", en: "Japan", zh: "日本" },
            { word: "毎日", kana: "まいにち", en: "every day", zh: "每天" },
            { word: "日曜日", kana: "にちようび", en: "Sunday", zh: "星期日" }] },
  { kanji: "月", on: ["ゲツ", "ガツ"], kun: ["つき"], en: "moon; month", zh: "月亮；月份",
    words: [{ word: "月曜日", kana: "げつようび", en: "Monday", zh: "星期一" },
            { word: "今月", kana: "こんげつ", en: "this month", zh: "这个月" },
            { word: "月", kana: "つき", en: "moon", zh: "月亮" }] },
  { kanji: "火", on: ["カ"], kun: ["ひ"], en: "fire", zh: "火",
    words: [{ word: "火曜日", kana: "かようび", en: "Tuesday", zh: "星期二" },
            { word: "火", kana: "ひ", en: "fire", zh: "火" }] },
  { kanji: "水", on: ["スイ"], kun: ["みず"], en: "water", zh: "水（日语「水」多指凉水，热水叫「お湯」）",
    words: [{ word: "水", kana: "みず", en: "water", zh: "水；凉水" },
            { word: "水曜日", kana: "すいようび", en: "Wednesday", zh: "星期三" }] },
  { kanji: "木", on: ["モク", "ボク"], kun: ["き"], en: "tree; wood", zh: "树；木",
    words: [{ word: "木曜日", kana: "もくようび", en: "Thursday", zh: "星期四" },
            { word: "木", kana: "き", en: "tree", zh: "树" }] },
  { kanji: "金", on: ["キン", "コン"], kun: ["かね"], en: "gold; money", zh: "金；钱",
    words: [{ word: "金曜日", kana: "きんようび", en: "Friday", zh: "星期五" },
            { word: "お金", kana: "おかね", en: "money", zh: "钱（不是“黄金”）" }] },
  { kanji: "土", on: ["ド", "ト"], kun: ["つち"], en: "earth; soil", zh: "土；土地",
    words: [{ word: "土曜日", kana: "どようび", en: "Saturday", zh: "星期六" },
            { word: "土", kana: "つち", en: "soil; earth", zh: "泥土" }] },

  // ---- People ----
  { kanji: "人", on: ["ジン", "ニン"], kun: ["ひと"], en: "person", zh: "人",
    words: [{ word: "日本人", kana: "にほんじん", en: "Japanese person", zh: "日本人" },
            { word: "三人", kana: "さんにん", en: "three people", zh: "三个人" },
            { word: "人", kana: "ひと", en: "person", zh: "人" }] },
  { kanji: "子", on: ["シ"], kun: ["こ"], en: "child", zh: "孩子；子",
    words: [{ word: "子ども", kana: "こども", en: "child", zh: "孩子" },
            { word: "女の子", kana: "おんなのこ", en: "girl", zh: "女孩" }] },
  { kanji: "女", on: ["ジョ", "ニョ"], kun: ["おんな"], en: "woman; female", zh: "女；女性",
    words: [{ word: "女の人", kana: "おんなのひと", en: "woman", zh: "女人；女士" },
            { word: "彼女", kana: "かのじょ", en: "she; girlfriend", zh: "她；女朋友" }] },
  { kanji: "男", on: ["ダン", "ナン"], kun: ["おとこ"], en: "man; male", zh: "男；男性",
    words: [{ word: "男の人", kana: "おとこのひと", en: "man", zh: "男人；男士" },
            { word: "男の子", kana: "おとこのこ", en: "boy", zh: "男孩" }] },
  { kanji: "父", on: ["フ"], kun: ["ちち"], en: "father", zh: "父亲",
    words: [{ word: "父", kana: "ちち", en: "(my) father", zh: "（自己的）父亲" },
            { word: "お父さん", kana: "おとうさん", en: "father (polite / addressing)", zh: "爸爸；（别人的）父亲" }] },
  { kanji: "母", on: ["ボ"], kun: ["はは"], en: "mother", zh: "母亲",
    words: [{ word: "母", kana: "はは", en: "(my) mother", zh: "（自己的）母亲" },
            { word: "お母さん", kana: "おかあさん", en: "mother (polite / addressing)", zh: "妈妈；（别人的）母亲" }] },
  { kanji: "友", on: ["ユウ"], kun: ["とも"], en: "friend", zh: "朋友",
    words: [{ word: "友だち", kana: "ともだち", en: "friend", zh: "朋友" },
            { word: "友人", kana: "ゆうじん", en: "friend (formal)", zh: "朋友（书面）" }] },

  // ---- Sizes and positions ----
  { kanji: "大", on: ["ダイ", "タイ"], kun: ["おお", "おお.きい"], en: "big", zh: "大",
    words: [{ word: "大きい", kana: "おおきい", en: "big", zh: "大的" },
            { word: "大学", kana: "だいがく", en: "university", zh: "大学" },
            { word: "大人", kana: "おとな", en: "adult", zh: "大人；成年人" }] },
  { kanji: "小", on: ["ショウ"], kun: ["ちい.さい", "こ", "お"], en: "small", zh: "小",
    words: [{ word: "小さい", kana: "ちいさい", en: "small", zh: "小的" },
            { word: "小学校", kana: "しょうがっこう", en: "elementary school", zh: "小学" }] },
  { kanji: "上", on: ["ジョウ"], kun: ["うえ", "あ.げる", "のぼ.る"], en: "up; above", zh: "上；上面",
    words: [{ word: "上", kana: "うえ", en: "above; on top", zh: "上面" },
            { word: "上手", kana: "じょうず", en: "skillful; good at", zh: "擅长；（技术）好（≠ 中文“上手/开始熟悉”）" }] },
  { kanji: "下", on: ["カ", "ゲ"], kun: ["した", "さ.がる", "くだ.さる"], en: "down; below", zh: "下；下面",
    words: [{ word: "下", kana: "した", en: "below; under", zh: "下面" },
            { word: "地下鉄", kana: "ちかてつ", en: "subway", zh: "地铁" },
            { word: "下手", kana: "へた", en: "unskillful; bad at", zh: "不擅长；笨拙" }] },
  { kanji: "中", on: ["チュウ", "ジュウ"], kun: ["なか"], en: "middle; inside", zh: "中；里面",
    words: [{ word: "中", kana: "なか", en: "inside", zh: "里面" },
            { word: "中国", kana: "ちゅうごく", en: "China", zh: "中国" },
            { word: "一日中", kana: "いちにちじゅう", en: "all day long", zh: "一整天" }] },
  { kanji: "右", on: ["ウ", "ユウ"], kun: ["みぎ"], en: "right", zh: "右",
    words: [{ word: "右", kana: "みぎ", en: "right (side)", zh: "右边" },
            { word: "右手", kana: "みぎて", en: "right hand", zh: "右手" }] },
  { kanji: "左", on: ["サ"], kun: ["ひだり"], en: "left", zh: "左",
    words: [{ word: "左", kana: "ひだり", en: "left (side)", zh: "左边" },
            { word: "左手", kana: "ひだりて", en: "left hand", zh: "左手" }] },
  { kanji: "前", on: ["ゼン"], kun: ["まえ"], en: "front; before", zh: "前；之前",
    words: [{ word: "前", kana: "まえ", en: "front; before", zh: "前面；以前" },
            { word: "午前", kana: "ごぜん", en: "morning; a.m.", zh: "上午" },
            { word: "名前", kana: "なまえ", en: "name", zh: "名字" }] },
  { kanji: "後", on: ["ゴ", "コウ"], kun: ["うし.ろ", "あと", "のち"], en: "behind; after", zh: "后；之后",
    words: [{ word: "後ろ", kana: "うしろ", en: "behind; back", zh: "后面" },
            { word: "午後", kana: "ごご", en: "afternoon; p.m.", zh: "下午" },
            { word: "後で", kana: "あとで", en: "later", zh: "待会儿；以后" }] },
  { kanji: "外", on: ["ガイ", "ゲ"], kun: ["そと", "ほか"], en: "outside", zh: "外；外面",
    words: [{ word: "外", kana: "そと", en: "outside", zh: "外面" },
            { word: "外国", kana: "がいこく", en: "foreign country", zh: "外国" },
            { word: "外国人", kana: "がいこくじん", en: "foreigner", zh: "外国人" }] },

  // ---- Time ----
  { kanji: "年", on: ["ネン"], kun: ["とし"], en: "year", zh: "年",
    words: [{ word: "今年", kana: "ことし", en: "this year", zh: "今年" },
            { word: "来年", kana: "らいねん", en: "next year", zh: "明年" },
            { word: "去年", kana: "きょねん", en: "last year", zh: "去年" }] },
  { kanji: "時", on: ["ジ"], kun: ["とき"], en: "time; hour; o'clock", zh: "时；点钟",
    words: [{ word: "時間", kana: "じかん", en: "time; hour(s)", zh: "时间；小时" },
            { word: "一時", kana: "いちじ", en: "one o'clock", zh: "一点钟" },
            { word: "時計", kana: "とけい", en: "clock; watch", zh: "钟表" }] },
  { kanji: "分", on: ["ブン", "フン", "ブ"], kun: ["わ.かる", "わ.ける"], en: "minute; part; understand", zh: "分钟；部分；明白",
    words: [{ word: "分かる", kana: "わかる", en: "to understand", zh: "明白；懂" },
            { word: "五分", kana: "ごふん", en: "five minutes", zh: "五分钟" },
            { word: "自分", kana: "じぶん", en: "oneself", zh: "自己" }] },
  { kanji: "半", on: ["ハン"], kun: ["なか.ば"], en: "half", zh: "半",
    words: [{ word: "半分", kana: "はんぶん", en: "half", zh: "一半" },
            { word: "三時半", kana: "さんじはん", en: "half past three", zh: "三点半" }] },
  { kanji: "今", on: ["コン"], kun: ["いま"], en: "now", zh: "现在；今",
    words: [{ word: "今", kana: "いま", en: "now", zh: "现在" },
            { word: "今日", kana: "きょう", en: "today", zh: "今天" },
            { word: "今晩", kana: "こんばん", en: "this evening; tonight", zh: "今晚" }] },
  { kanji: "先", on: ["セン"], kun: ["さき"], en: "previous; ahead", zh: "先；前面；上一个",
    words: [{ word: "先生", kana: "せんせい", en: "teacher; doctor", zh: "老师；医生（≠ 中文“先生/Mr.”）" },
            { word: "先週", kana: "せんしゅう", en: "last week", zh: "上周" },
            { word: "先に", kana: "さきに", en: "first; ahead", zh: "先；提前" }] },
  { kanji: "毎", on: ["マイ"], kun: [], en: "every", zh: "每",
    words: [{ word: "毎日", kana: "まいにち", en: "every day", zh: "每天" },
            { word: "毎朝", kana: "まいあさ", en: "every morning", zh: "每天早上" },
            { word: "毎週", kana: "まいしゅう", en: "every week", zh: "每周" }] },
  { kanji: "週", on: ["シュウ"], kun: [], en: "week", zh: "周；星期",
    words: [{ word: "今週", kana: "こんしゅう", en: "this week", zh: "这周" },
            { word: "来週", kana: "らいしゅう", en: "next week", zh: "下周" },
            { word: "週末", kana: "しゅうまつ", en: "weekend", zh: "周末" }] },
  { kanji: "午", on: ["ゴ"], kun: [], en: "noon", zh: "午",
    words: [{ word: "午前", kana: "ごぜん", en: "morning; a.m.", zh: "上午" },
            { word: "午後", kana: "ごご", en: "afternoon; p.m.", zh: "下午" }] },

  // ---- Verbs ----
  { kanji: "行", on: ["コウ", "ギョウ"], kun: ["い.く", "おこな.う"], en: "go", zh: "去；行",
    words: [{ word: "行く", kana: "いく", en: "to go", zh: "去" },
            { word: "銀行", kana: "ぎんこう", en: "bank", zh: "银行" },
            { word: "旅行", kana: "りょこう", en: "trip; travel", zh: "旅行" }] },
  { kanji: "来", on: ["ライ"], kun: ["く.る"], en: "come", zh: "来",
    words: [{ word: "来る", kana: "くる", en: "to come", zh: "来" },
            { word: "来週", kana: "らいしゅう", en: "next week", zh: "下周" },
            { word: "来年", kana: "らいねん", en: "next year", zh: "明年" }] },
  { kanji: "見", on: ["ケン"], kun: ["み.る", "み.せる"], en: "see; look", zh: "看；见",
    words: [{ word: "見る", kana: "みる", en: "to see; to watch", zh: "看" },
            { word: "見せる", kana: "みせる", en: "to show", zh: "给……看" }] },
  { kanji: "聞", on: ["ブン", "モン"], kun: ["き.く"], en: "hear; ask", zh: "听；问",
    words: [{ word: "聞く", kana: "きく", en: "to listen; to ask", zh: "听；问" },
            { word: "新聞", kana: "しんぶん", en: "newspaper", zh: "报纸（≠ 中文“新闻”）" }] },
  { kanji: "話", on: ["ワ"], kun: ["はな.す", "はなし"], en: "speak; talk", zh: "说话；话",
    words: [{ word: "話す", kana: "はなす", en: "to speak; to talk", zh: "说；讲" },
            { word: "電話", kana: "でんわ", en: "telephone", zh: "电话" },
            { word: "話", kana: "はなし", en: "talk; story", zh: "话；故事" }] },
  { kanji: "言", on: ["ゲン", "ゴン"], kun: ["い.う", "こと"], en: "say; word", zh: "说；言",
    words: [{ word: "言う", kana: "いう", en: "to say", zh: "说" },
            { word: "言葉", kana: "ことば", en: "word; language", zh: "词语；语言" }] },
  { kanji: "読", on: ["ドク"], kun: ["よ.む"], en: "read", zh: "读",
    words: [{ word: "読む", kana: "よむ", en: "to read", zh: "读；看（书）" },
            { word: "読書", kana: "どくしょ", en: "reading (books)", zh: "读书；阅读" }] },
  { kanji: "書", on: ["ショ"], kun: ["か.く"], en: "write", zh: "写；书",
    words: [{ word: "書く", kana: "かく", en: "to write", zh: "写" },
            { word: "辞書", kana: "じしょ", en: "dictionary", zh: "词典" },
            { word: "図書館", kana: "としょかん", en: "library", zh: "图书馆" }] },
  { kanji: "食", on: ["ショク"], kun: ["た.べる"], en: "eat; food", zh: "吃；食物",
    words: [{ word: "食べる", kana: "たべる", en: "to eat", zh: "吃" },
            { word: "食堂", kana: "しょくどう", en: "cafeteria; dining hall", zh: "食堂" },
            { word: "食べ物", kana: "たべもの", en: "food", zh: "食物" }] },
  { kanji: "飲", on: ["イン"], kun: ["の.む"], en: "drink", zh: "喝；饮",
    words: [{ word: "飲む", kana: "のむ", en: "to drink; to take (medicine)", zh: "喝；吃（药）" },
            { word: "飲み物", kana: "のみもの", en: "drink; beverage", zh: "饮料" }] },
  { kanji: "買", on: ["バイ"], kun: ["か.う"], en: "buy", zh: "买",
    words: [{ word: "買う", kana: "かう", en: "to buy", zh: "买" },
            { word: "買い物", kana: "かいもの", en: "shopping", zh: "购物" }] },
  { kanji: "休", on: ["キュウ"], kun: ["やす.む", "やす.み"], en: "rest", zh: "休息",
    words: [{ word: "休む", kana: "やすむ", en: "to rest; to take a day off", zh: "休息；请假" },
            { word: "休み", kana: "やすみ", en: "break; holiday; day off", zh: "休息；假期" },
            { word: "夏休み", kana: "なつやすみ", en: "summer vacation", zh: "暑假" }] },
  { kanji: "入", on: ["ニュウ"], kun: ["はい.る", "い.れる"], en: "enter; put in", zh: "进入；放入",
    words: [{ word: "入る", kana: "はいる", en: "to enter", zh: "进入" },
            { word: "入れる", kana: "いれる", en: "to put in", zh: "放进" },
            { word: "入口", kana: "いりぐち", en: "entrance", zh: "入口" }] },
  { kanji: "出", on: ["シュツ"], kun: ["で.る", "だ.す"], en: "exit; go out", zh: "出",
    words: [{ word: "出る", kana: "でる", en: "to go out; to leave", zh: "出去；离开" },
            { word: "出す", kana: "だす", en: "to take out; to submit", zh: "拿出；提交" },
            { word: "出口", kana: "でぐち", en: "exit", zh: "出口" }] },
  { kanji: "会", on: ["カイ", "エ"], kun: ["あ.う"], en: "meet; meeting", zh: "见面；会",
    words: [{ word: "会う", kana: "あう", en: "to meet", zh: "见面（≠ 中文“会/能”）" },
            { word: "会社", kana: "かいしゃ", en: "company", zh: "公司" }] },

  // ---- Common nouns and adjectives ----
  { kanji: "山", on: ["サン"], kun: ["やま"], en: "mountain", zh: "山",
    words: [{ word: "山", kana: "やま", en: "mountain", zh: "山" },
            { word: "富士山", kana: "ふじさん", en: "Mt. Fuji", zh: "富士山" }] },
  { kanji: "川", on: ["セン"], kun: ["かわ"], en: "river", zh: "河；川",
    words: [{ word: "川", kana: "かわ", en: "river", zh: "河" },
            { word: "小川", kana: "おがわ", en: "stream; brook", zh: "小河" }] },
  { kanji: "気", on: ["キ", "ケ"], kun: [], en: "spirit; mood; air", zh: "气；精神；心情",
    words: [{ word: "元気", kana: "げんき", en: "healthy; energetic", zh: "健康；有精神" },
            { word: "天気", kana: "てんき", en: "weather", zh: "天气" },
            { word: "人気", kana: "にんき", en: "popularity", zh: "人气；受欢迎" }] },
  { kanji: "雨", on: ["ウ"], kun: ["あめ", "あま"], en: "rain", zh: "雨",
    words: [{ word: "雨", kana: "あめ", en: "rain", zh: "雨" },
            { word: "大雨", kana: "おおあめ", en: "heavy rain", zh: "大雨" }] },
  { kanji: "天", on: ["テン"], kun: ["あま", "あめ"], en: "heaven; sky", zh: "天；天空",
    words: [{ word: "天気", kana: "てんき", en: "weather", zh: "天气" },
            { word: "天ぷら", kana: "てんぷら", en: "tempura", zh: "天妇罗" }] },
  { kanji: "学", on: ["ガク"], kun: ["まな.ぶ"], en: "study; learning", zh: "学；学习",
    words: [{ word: "学生", kana: "がくせい", en: "student", zh: "学生（多指大学生）" },
            { word: "大学", kana: "だいがく", en: "university", zh: "大学" },
            { word: "学校", kana: "がっこう", en: "school", zh: "学校" }] },
  { kanji: "校", on: ["コウ"], kun: [], en: "school", zh: "学校",
    words: [{ word: "学校", kana: "がっこう", en: "school", zh: "学校" },
            { word: "高校", kana: "こうこう", en: "high school", zh: "高中" }] },
  { kanji: "生", on: ["セイ", "ショウ"], kun: ["い.きる", "う.まれる", "なま"], en: "life; be born; raw", zh: "生；出生；生的",
    words: [{ word: "先生", kana: "せんせい", en: "teacher", zh: "老师" },
            { word: "生まれる", kana: "うまれる", en: "to be born", zh: "出生" },
            { word: "誕生日", kana: "たんじょうび", en: "birthday", zh: "生日" }] },
  { kanji: "名", on: ["メイ", "ミョウ"], kun: ["な"], en: "name", zh: "名；名字",
    words: [{ word: "名前", kana: "なまえ", en: "name", zh: "名字" },
            { word: "有名", kana: "ゆうめい", en: "famous", zh: "有名" }] },
  { kanji: "本", on: ["ホン"], kun: ["もと"], en: "book; origin", zh: "书；根本",
    words: [{ word: "本", kana: "ほん", en: "book", zh: "书" },
            { word: "日本", kana: "にほん", en: "Japan", zh: "日本" },
            { word: "一本", kana: "いっぽん", en: "one (long, thin object)", zh: "一根；一瓶；一支" }] },
  { kanji: "何", on: [], kun: ["なに", "なん"], en: "what", zh: "什么",
    words: [{ word: "何", kana: "なに", en: "what", zh: "什么" },
            { word: "何人", kana: "なんにん", en: "how many people", zh: "几个人" },
            { word: "何時", kana: "なんじ", en: "what time", zh: "几点" }] },
  { kanji: "国", on: ["コク"], kun: ["くに"], en: "country", zh: "国家",
    words: [{ word: "国", kana: "くに", en: "country; home country", zh: "国家；祖国" },
            { word: "中国", kana: "ちゅうごく", en: "China", zh: "中国" },
            { word: "外国", kana: "がいこく", en: "foreign country", zh: "外国" }] },
  { kanji: "語", on: ["ゴ"], kun: ["かた.る"], en: "language; word", zh: "语言；语",
    words: [{ word: "日本語", kana: "にほんご", en: "Japanese (language)", zh: "日语" },
            { word: "英語", kana: "えいご", en: "English (language)", zh: "英语" },
            { word: "中国語", kana: "ちゅうごくご", en: "Chinese (language)", zh: "汉语；中文" }] },
  { kanji: "白", on: ["ハク"], kun: ["しろ", "しろ.い"], en: "white", zh: "白",
    words: [{ word: "白い", kana: "しろい", en: "white", zh: "白色的" },
            { word: "面白い", kana: "おもしろい", en: "interesting; funny", zh: "有趣（不是“白色”的意思）" }] },
  { kanji: "高", on: ["コウ"], kun: ["たか.い"], en: "tall; high; expensive", zh: "高；贵",
    words: [{ word: "高い", kana: "たかい", en: "tall; high; expensive", zh: "高；贵" },
            { word: "高校", kana: "こうこう", en: "high school", zh: "高中" }] },
  { kanji: "新", on: ["シン"], kun: ["あたら.しい"], en: "new", zh: "新",
    words: [{ word: "新しい", kana: "あたらしい", en: "new", zh: "新的" },
            { word: "新聞", kana: "しんぶん", en: "newspaper", zh: "报纸（≠ 中文“新闻”）" }] },
  { kanji: "東", on: ["トウ"], kun: ["ひがし"], en: "east", zh: "东",
    words: [{ word: "東", kana: "ひがし", en: "east", zh: "东" },
            { word: "東京", kana: "とうきょう", en: "Tokyo", zh: "东京" }] },
  { kanji: "西", on: ["セイ", "サイ"], kun: ["にし"], en: "west", zh: "西",
    words: [{ word: "西", kana: "にし", en: "west", zh: "西" },
            { word: "関西", kana: "かんさい", en: "Kansai region", zh: "关西（地区）" }] },
  { kanji: "南", on: ["ナン"], kun: ["みなみ"], en: "south", zh: "南",
    words: [{ word: "南", kana: "みなみ", en: "south", zh: "南" },
            { word: "南口", kana: "みなみぐち", en: "south exit / entrance", zh: "南口" }] },
  { kanji: "北", on: ["ホク"], kun: ["きた"], en: "north", zh: "北",
    words: [{ word: "北", kana: "きた", en: "north", zh: "北" },
            { word: "北口", kana: "きたぐち", en: "north exit / entrance", zh: "北口" }] },
  { kanji: "電", on: ["デン"], kun: [], en: "electricity", zh: "电",
    words: [{ word: "電車", kana: "でんしゃ", en: "train", zh: "电车；（城市）列车" },
            { word: "電話", kana: "でんわ", en: "telephone", zh: "电话" },
            { word: "電気", kana: "でんき", en: "electricity; light", zh: "电；电灯" }] },
  { kanji: "車", on: ["シャ"], kun: ["くるま"], en: "car; vehicle", zh: "车",
    words: [{ word: "車", kana: "くるま", en: "car", zh: "汽车" },
            { word: "電車", kana: "でんしゃ", en: "train", zh: "电车；列车" },
            { word: "自転車", kana: "じてんしゃ", en: "bicycle", zh: "自行车" }] },
  { kanji: "駅", on: ["エキ"], kun: [], en: "station", zh: "车站",
    words: [{ word: "駅", kana: "えき", en: "station", zh: "车站" },
            { word: "駅前", kana: "えきまえ", en: "in front of the station", zh: "车站前" }] },
  { kanji: "店", on: ["テン"], kun: ["みせ"], en: "shop; store", zh: "店；商店",
    words: [{ word: "店", kana: "みせ", en: "shop; store", zh: "商店" },
            { word: "喫茶店", kana: "きっさてん", en: "café; coffee shop", zh: "咖啡馆；茶馆" },
            { word: "店員", kana: "てんいん", en: "shop clerk", zh: "店员" }] },
  { kanji: "間", on: ["カン", "ケン"], kun: ["あいだ", "ま"], en: "interval; between", zh: "间；之间",
    words: [{ word: "時間", kana: "じかん", en: "time; hour(s)", zh: "时间；小时" },
            { word: "間", kana: "あいだ", en: "between; during", zh: "之间；期间" },
            { word: "人間", kana: "にんげん", en: "human being", zh: "人；人类（≠ 中文“人间”）" }] },
  { kanji: "手", on: ["シュ"], kun: ["て"], en: "hand", zh: "手",
    words: [{ word: "手", kana: "て", en: "hand", zh: "手" },
            { word: "手紙", kana: "てがみ", en: "letter (mail)", zh: "信（≠ 中文“手纸/卫生纸”）" },
            { word: "上手", kana: "じょうず", en: "skillful", zh: "擅长" }] },
  { kanji: "口", on: ["コウ", "ク"], kun: ["くち", "-ぐち"], en: "mouth; opening", zh: "口；嘴",
    words: [{ word: "口", kana: "くち", en: "mouth", zh: "嘴" },
            { word: "入口", kana: "いりぐち", en: "entrance", zh: "入口" },
            { word: "出口", kana: "でぐち", en: "exit", zh: "出口" }] },
  { kanji: "目", on: ["モク"], kun: ["め"], en: "eye", zh: "眼睛；目",
    words: [{ word: "目", kana: "め", en: "eye", zh: "眼睛" },
            { word: "二つ目", kana: "ふたつめ", en: "the second (one)", zh: "第二个" }] },
];
