// Built-in vocabulary deck (JLPT N5). Entries are introduced in this order.
// word: as usually written (kanji or kana); kana: full reading in hiragana/katakana;
// accent: Tokyo pitch-accent number (0 = flat) or null if unsure; ex: one example sentence
// (jp as written, kana = its full reading, en, zh).
export const VOCAB = [
  {word: "おはようございます",kana: "おはようございます",accent: null,en: "good morning",zh: "早上好",ex: {jp: "先生、おはようございます。",kana: "せんせい、おはようございます。",en: "Good morning, teacher.",zh: "老师，早上好。"}},
  {word: "こんにちは",kana: "こんにちは",accent: null,en: "hello; good afternoon",zh: "你好（白天）",ex: {jp: "こんにちは。いい天気ですね。",kana: "こんにちは。いいてんきですね。",en: "Hello. Nice weather, isn't it?",zh: "你好。天气真好啊。"}},
  {word: "こんばんは",kana: "こんばんは",accent: null,en: "good evening",zh: "晚上好",ex: {jp: "こんばんは。今日は寒いですね。",kana: "こんばんは。きょうはさむいですね。",en: "Good evening. It's cold today, isn't it?",zh: "晚上好。今天真冷啊。"}},
  {word: "ありがとうございます",kana: "ありがとうございます",accent: null,en: "thank you",zh: "谢谢",ex: {jp: "手紙をありがとうございます。",kana: "てがみをありがとうございます。",en: "Thank you for the letter.",zh: "谢谢你的信。"}},
  {word: "すみません",kana: "すみません",accent: null,en: "excuse me; I'm sorry",zh: "不好意思；对不起",ex: {jp: "すみません、駅はどこですか。",kana: "すみません、えきはどこですか。",en: "Excuse me, where is the station?",zh: "不好意思，车站在哪里？"}},
  {word: "ごめんなさい",kana: "ごめんなさい",accent: null,en: "I'm sorry",zh: "对不起",ex: {jp: "おそくなって、ごめんなさい。",kana: "おそくなって、ごめんなさい。",en: "Sorry I'm late.",zh: "对不起，我来晚了。"}},
  {word: "いただきます",kana: "いただきます",accent: null,en: "(said before eating)",zh: "我开动了（饭前用语）",ex: {jp: "「いただきます。」と言ってから食べます。",kana: "「いただきます。」といってからたべます。",en: "We say “itadakimasu” before we eat.",zh: "说完“いただきます”再吃。"}},
  {word: "ごちそうさまでした",kana: "ごちそうさまでした",accent: null,en: "(said after eating) thank you for the meal",zh: "我吃好了；多谢款待（饭后用语）",ex: {jp: "ごちそうさまでした。おいしかったです。",kana: "ごちそうさまでした。おいしかったです。",en: "Thank you for the meal. It was delicious.",zh: "我吃好了，很好吃。"}},
  {word: "さようなら",kana: "さようなら",accent: null,en: "goodbye",zh: "再见",ex: {jp: "先生、さようなら。",kana: "せんせい、さようなら。",en: "Goodbye, teacher.",zh: "老师，再见。"}},
  {word: "おやすみなさい",kana: "おやすみなさい",accent: null,en: "good night",zh: "晚安",ex: {jp: "もう十一時です。おやすみなさい。",kana: "もうじゅういちじです。おやすみなさい。",en: "It's already eleven. Good night.",zh: "已经十一点了，晚安。"}},
  {word: "はじめまして",kana: "はじめまして",accent: null,en: "nice to meet you (first meeting)",zh: "初次见面",ex: {jp: "はじめまして。リンです。",kana: "はじめまして。リンです。",en: "Nice to meet you. I'm Lin.",zh: "初次见面，我是林。"}},
  {word: "よろしくおねがいします",kana: "よろしくおねがいします",accent: null,en: "please treat me kindly; nice to meet you",zh: "请多关照",ex: {jp: "はじめまして。どうぞよろしくおねがいします。",kana: "はじめまして。どうぞよろしくおねがいします。",en: "Nice to meet you. I look forward to working with you.",zh: "初次见面，请多关照。"}},
  {word: "いってきます",kana: "いってきます",accent: null,en: "I'm off (said when leaving home)",zh: "我走了（出门时说）",ex: {jp: "「いってきます。」「いってらっしゃい。」",kana: "「いってきます。」「いってらっしゃい。」",en: "“I'm off.” “See you later.”",zh: "“我走了。”“路上小心。”"}},
  {word: "ただいま",kana: "ただいま",accent: null,en: "I'm home",zh: "我回来了",ex: {jp: "「ただいま。」「おかえりなさい。」",kana: "「ただいま。」「おかえりなさい。」",en: "“I'm home.” “Welcome back.”",zh: "“我回来了。”“你回来啦。”"}},
  {word: "わたし",kana: "わたし",accent: 0,en: "I; me",zh: "我",ex: {jp: "わたしは学生です。",kana: "わたしはがくせいです。",en: "I am a student.",zh: "我是学生。"}},
  {word: "あなた",kana: "あなた",accent: 2,en: "you (often avoided; use the person's name)",zh: "你（日语中常用对方名字代替）",ex: {jp: "あなたは学生ですか。",kana: "あなたはがくせいですか。",en: "Are you a student?",zh: "你是学生吗？"}},
  {word: "かれ",kana: "かれ",accent: 1,en: "he; boyfriend",zh: "他；男朋友",ex: {jp: "かれは日本人です。",kana: "かれはにほんじんです。",en: "He is Japanese.",zh: "他是日本人。"}},
  {word: "かのじょ",kana: "かのじょ",accent: 1,en: "she; girlfriend",zh: "她；女朋友",ex: {jp: "かのじょは先生です。",kana: "かのじょはせんせいです。",en: "She is a teacher.",zh: "她是老师。"}},
  {word: "人",kana: "ひと",accent: 0,en: "person",zh: "人",ex: {jp: "あの人はだれですか。",kana: "あのひとはだれですか。",en: "Who is that person?",zh: "那个人是谁？"}},
  {word: "男の人",kana: "おとこのひと",accent: null,en: "man",zh: "男人；男士",ex: {jp: "男の人が三人います。",kana: "おとこのひとがさんにんいます。",en: "There are three men.",zh: "有三个男人。"}},
  {word: "女の人",kana: "おんなのひと",accent: null,en: "woman",zh: "女人；女士",ex: {jp: "あの女の人はわたしの母です。",kana: "あのおんなのひとはわたしのははです。",en: "That woman is my mother.",zh: "那位女士是我妈妈。"}},
  {word: "子ども",kana: "こども",accent: 0,en: "child",zh: "孩子；小孩",ex: {jp: "子どもが二人います。",kana: "こどもがふたりいます。",en: "I have two children.",zh: "我有两个孩子。"}},
  {word: "友だち",kana: "ともだち",accent: 0,en: "friend",zh: "朋友",ex: {jp: "友だちとこうえんへ行きます。",kana: "ともだちとこうえんへいきます。",en: "I'm going to the park with a friend.",zh: "我和朋友去公园。"}},
  {word: "先生",kana: "せんせい",accent: 3,en: "teacher; doctor",zh: "老师；（对医生等的尊称）（不是“先生/Mr.”）",ex: {jp: "先生、しつもんがあります。",kana: "せんせい、しつもんがあります。",en: "Teacher, I have a question.",zh: "老师，我有个问题。"}},
  {word: "学生",kana: "がくせい",accent: 0,en: "student (esp. university)",zh: "学生（多指大学生）",ex: {jp: "わたしは大学の学生です。",kana: "わたしはだいがくのがくせいです。",en: "I am a university student.",zh: "我是大学生。"}},
  {word: "家族",kana: "かぞく",accent: 1,en: "family",zh: "家人；家庭",ex: {jp: "家族は四人です。",kana: "かぞくはよにんです。",en: "There are four people in my family.",zh: "我家有四口人。"}},
  {word: "父",kana: "ちち",accent: 2,en: "(my) father",zh: "父亲（称自己的父亲）",ex: {jp: "父は会社員です。",kana: "ちちはかいしゃいんです。",en: "My father is an office worker.",zh: "我父亲是公司职员。"}},
  {word: "母",kana: "はは",accent: 1,en: "(my) mother",zh: "母亲（称自己的母亲）",ex: {jp: "母はとても元気です。",kana: "はははとてもげんきです。",en: "My mother is very well.",zh: "我母亲身体很好。"}},
  {word: "お父さん",kana: "おとうさん",accent: 2,en: "father (someone else's; or Dad)",zh: "爸爸；（别人的）父亲",ex: {jp: "お父さんはお元気ですか。",kana: "おとうさんはおげんきですか。",en: "How is your father?",zh: "你父亲身体好吗？"}},
  {word: "お母さん",kana: "おかあさん",accent: 2,en: "mother (someone else's; or Mom)",zh: "妈妈；（别人的）母亲",ex: {jp: "お母さん、ただいま。",kana: "おかあさん、ただいま。",en: "Mom, I'm home.",zh: "妈妈，我回来了。"}},
  {word: "兄",kana: "あに",accent: 1,en: "(my) older brother",zh: "哥哥（称自己的）",ex: {jp: "兄は東京にいます。",kana: "あにはとうきょうにいます。",en: "My older brother is in Tokyo.",zh: "我哥哥在东京。"}},
  {word: "姉",kana: "あね",accent: 0,en: "(my) older sister",zh: "姐姐（称自己的）",ex: {jp: "姉はテニスが好きです。",kana: "あねはテニスがすきです。",en: "My older sister likes tennis.",zh: "我姐姐喜欢网球。"}},
  {word: "弟",kana: "おとうと",accent: 4,en: "(my) younger brother",zh: "弟弟",ex: {jp: "弟は十さいです。",kana: "おとうとはじゅっさいです。",en: "My younger brother is ten.",zh: "我弟弟十岁。"}},
  {word: "妹",kana: "いもうと",accent: 4,en: "(my) younger sister",zh: "妹妹",ex: {jp: "妹も学生です。",kana: "いもうともがくせいです。",en: "My younger sister is a student too.",zh: "我妹妹也是学生。"}},
  {word: "一つ",kana: "ひとつ",accent: 2,en: "one (thing)",zh: "一个",ex: {jp: "いすが一つあります。",kana: "いすがひとつあります。",en: "There is one chair.",zh: "有一把椅子。"}},
  {word: "二つ",kana: "ふたつ",accent: 3,en: "two (things)",zh: "两个",ex: {jp: "かばんが二つあります。",kana: "かばんがふたつあります。",en: "There are two bags.",zh: "有两个包。"}},
  {word: "三つ",kana: "みっつ",accent: 3,en: "three (things)",zh: "三个",ex: {jp: "おかしを三つ買いました。",kana: "おかしをみっつかいました。",en: "I bought three snacks.",zh: "我买了三个点心。"}},
  {word: "四つ",kana: "よっつ",accent: 3,en: "four (things)",zh: "四个",ex: {jp: "りんごを四つください。",kana: "りんごをよっつください。",en: "Four apples, please.",zh: "请给我四个苹果。"}},
  {word: "五つ",kana: "いつつ",accent: 2,en: "five (things)",zh: "五个",ex: {jp: "たまごが五つあります。",kana: "たまごがいつつあります。",en: "There are five eggs.",zh: "有五个鸡蛋。"}},
  {word: "六つ",kana: "むっつ",accent: 3,en: "six (things)",zh: "六个",ex: {jp: "いすが六つあります。",kana: "いすがむっつあります。",en: "There are six chairs.",zh: "有六把椅子。"}},
  {word: "七つ",kana: "ななつ",accent: 2,en: "seven (things)",zh: "七个",ex: {jp: "かぎが七つあります。",kana: "かぎがななつあります。",en: "There are seven keys.",zh: "有七把钥匙。"}},
  {word: "八つ",kana: "やっつ",accent: 3,en: "eight (things)",zh: "八个",ex: {jp: "みかんを八つ買いました。",kana: "みかんをやっつかいました。",en: "I bought eight mandarin oranges.",zh: "我买了八个橘子。"}},
  {word: "九つ",kana: "ここのつ",accent: 2,en: "nine (things)",zh: "九个",ex: {jp: "りんごが九つあります。",kana: "りんごがここのつあります。",en: "There are nine apples.",zh: "有九个苹果。"}},
  {word: "十",kana: "とお",accent: 1,en: "ten (things); ten years old",zh: "十个；十岁",ex: {jp: "子どもは十になりました。",kana: "こどもはとおになりました。",en: "My child turned ten.",zh: "孩子十岁了。"}},
  {word: "何人",kana: "なんにん",accent: 1,en: "how many people",zh: "几个人",ex: {jp: "家族は何人ですか。",kana: "かぞくはなんにんですか。",en: "How many people are in your family?",zh: "你家有几口人？"}},
  {word: "一人",kana: "ひとり",accent: 2,en: "one person; alone",zh: "一个人",ex: {jp: "一人で行きます。",kana: "ひとりでいきます。",en: "I'll go alone.",zh: "我一个人去。"}},
  {word: "二人",kana: "ふたり",accent: 3,en: "two people",zh: "两个人",ex: {jp: "二人で昼ごはんを食べました。",kana: "ふたりでひるごはんをたべました。",en: "The two of us had lunch together.",zh: "我们两个人一起吃了午饭。"}},
  {word: "今",kana: "いま",accent: 1,en: "now",zh: "现在",ex: {jp: "今、何時ですか。",kana: "いま、なんじですか。",en: "What time is it now?",zh: "现在几点？"}},
  {word: "今日",kana: "きょう",accent: 1,en: "today",zh: "今天",ex: {jp: "今日は休みです。",kana: "きょうはやすみです。",en: "Today is my day off.",zh: "今天休息。"}},
  {word: "明日",kana: "あした",accent: 3,en: "tomorrow",zh: "明天",ex: {jp: "明日、学校へ行きます。",kana: "あした、がっこうへいきます。",en: "I will go to school tomorrow.",zh: "明天去学校。"}},
  {word: "昨日",kana: "きのう",accent: 2,en: "yesterday",zh: "昨天",ex: {jp: "昨日、本を読みました。",kana: "きのう、ほんをよみました。",en: "I read a book yesterday.",zh: "昨天看了书。"}},
  {word: "毎日",kana: "まいにち",accent: 1,en: "every day",zh: "每天",ex: {jp: "毎日、日本語をべんきょうします。",kana: "まいにち、にほんごをべんきょうします。",en: "I study Japanese every day.",zh: "每天学习日语。"}},
  {word: "朝",kana: "あさ",accent: 1,en: "morning",zh: "早上；早晨",ex: {jp: "朝、コーヒーを飲みます。",kana: "あさ、コーヒーをのみます。",en: "I drink coffee in the morning.",zh: "早上喝咖啡。"}},
  {word: "昼",kana: "ひる",accent: 2,en: "noon; daytime; lunch",zh: "中午；白天；午饭",ex: {jp: "昼に友だちとあいます。",kana: "ひるにともだちとあいます。",en: "I'm meeting a friend at noon.",zh: "中午和朋友见面。"}},
  {word: "夜",kana: "よる",accent: 1,en: "night; evening",zh: "夜晚；晚上",ex: {jp: "夜はテレビを見ます。",kana: "よるはテレビをみます。",en: "I watch TV at night.",zh: "晚上看电视。"}},
  {word: "今年",kana: "ことし",accent: 0,en: "this year",zh: "今年",ex: {jp: "今年、日本へ行きます。",kana: "ことし、にほんへいきます。",en: "I'm going to Japan this year.",zh: "今年去日本。"}},
  {word: "来年",kana: "らいねん",accent: 0,en: "next year",zh: "明年",ex: {jp: "来年、大学に入ります。",kana: "らいねん、だいがくにはいります。",en: "I will start university next year.",zh: "明年上大学。"}},
  {word: "去年",kana: "きょねん",accent: 1,en: "last year",zh: "去年",ex: {jp: "去年、山にのぼりました。",kana: "きょねん、やまにのぼりました。",en: "I climbed a mountain last year.",zh: "去年爬了山。"}},
  {word: "週",kana: "しゅう",accent: 1,en: "week",zh: "周；星期",ex: {jp: "週に三日、アルバイトをします。",kana: "しゅうにみっか、アルバイトをします。",en: "I work part-time three days a week.",zh: "每周打工三天。"}},
  {word: "月",kana: "つき",accent: 2,en: "moon; month",zh: "月亮；月",ex: {jp: "空に月が出ています。",kana: "そらにつきがでています。",en: "The moon is out in the sky.",zh: "天上出了月亮。"}},
  {word: "年",kana: "とし",accent: 2,en: "year; age",zh: "年；年龄",ex: {jp: "父は母より年が上です。",kana: "ちちはははよりとしがうえです。",en: "My father is older than my mother.",zh: "爸爸比妈妈年纪大。"}},
  {word: "時間",kana: "じかん",accent: 0,en: "time; hour(s)",zh: "时间；小时",ex: {jp: "今日は時間がありません。",kana: "きょうはじかんがありません。",en: "I don't have time today.",zh: "今天没有时间。"}},
  {word: "午前",kana: "ごぜん",accent: 1,en: "morning; a.m.",zh: "上午",ex: {jp: "午前九時に会社へ行きます。",kana: "ごぜんくじにかいしゃへいきます。",en: "I go to the office at 9 a.m.",zh: "上午九点去公司。"}},
  {word: "午後",kana: "ごご",accent: 1,en: "afternoon; p.m.",zh: "下午",ex: {jp: "午後、友だちと話しました。",kana: "ごご、ともだちとはなしました。",en: "I talked with a friend in the afternoon.",zh: "下午和朋友聊了天。"}},
  {word: "半",kana: "はん",accent: 1,en: "half; half past",zh: "半；一半",ex: {jp: "七時半におきます。",kana: "しちじはんにおきます。",en: "I get up at half past seven.",zh: "七点半起床。"}},
  {word: "先週",kana: "せんしゅう",accent: 0,en: "last week",zh: "上周；上个星期",ex: {jp: "先週、あたらしいくつを買いました。",kana: "せんしゅう、あたらしいくつをかいました。",en: "I bought new shoes last week.",zh: "上周买了新鞋。"}},
  {word: "来週",kana: "らいしゅう",accent: 0,en: "next week",zh: "下周；下个星期",ex: {jp: "来週、テストがあります。",kana: "らいしゅう、テストがあります。",en: "There is a test next week.",zh: "下周有考试。"}},
  {word: "月曜日",kana: "げつようび",accent: 3,en: "Monday",zh: "星期一",ex: {jp: "月曜日はいそがしいです。",kana: "げつようびはいそがしいです。",en: "I'm busy on Mondays.",zh: "星期一很忙。"}},
  {word: "火曜日",kana: "かようび",accent: 2,en: "Tuesday",zh: "星期二",ex: {jp: "火曜日にプールへ行きます。",kana: "かようびにプールへいきます。",en: "I go to the pool on Tuesdays.",zh: "星期二去游泳池。"}},
  {word: "水曜日",kana: "すいようび",accent: 3,en: "Wednesday",zh: "星期三",ex: {jp: "水曜日は学校が休みです。",kana: "すいようびはがっこうがやすみです。",en: "There is no school on Wednesday.",zh: "星期三学校放假。"}},
  {word: "木曜日",kana: "もくようび",accent: 3,en: "Thursday",zh: "星期四",ex: {jp: "木曜日に先生と話します。",kana: "もくようびにせんせいとはなします。",en: "I will talk with the teacher on Thursday.",zh: "星期四和老师谈话。"}},
  {word: "金曜日",kana: "きんようび",accent: 3,en: "Friday",zh: "星期五",ex: {jp: "金曜日のばん、えいがを見ます。",kana: "きんようびのばん、えいがをみます。",en: "I'm going to see a movie on Friday evening.",zh: "星期五晚上看电影。"}},
  {word: "土曜日",kana: "どようび",accent: 2,en: "Saturday",zh: "星期六",ex: {jp: "土曜日にそうじをします。",kana: "どようびにそうじをします。",en: "I clean on Saturdays.",zh: "星期六打扫卫生。"}},
  {word: "日曜日",kana: "にちようび",accent: 3,en: "Sunday",zh: "星期日；星期天",ex: {jp: "日曜日はどこへも行きません。",kana: "にちようびはどこへもいきません。",en: "I don't go anywhere on Sundays.",zh: "星期天哪儿也不去。"}},
  {word: "家",kana: "いえ",accent: 2,en: "house; home",zh: "家；房子",ex: {jp: "家から駅まで五分です。",kana: "いえからえきまでごふんです。",en: "It's five minutes from my house to the station.",zh: "从我家到车站要五分钟。"}},
  {word: "学校",kana: "がっこう",accent: 0,en: "school",zh: "学校",ex: {jp: "学校までバスで行きます。",kana: "がっこうまでバスでいきます。",en: "I go to school by bus.",zh: "坐公交车去学校。"}},
  {word: "駅",kana: "えき",accent: 1,en: "station",zh: "车站",ex: {jp: "駅はどこですか。",kana: "えきはどこですか。",en: "Where is the station?",zh: "车站在哪里？"}},
  {word: "店",kana: "みせ",accent: 2,en: "shop; store",zh: "店；商店",ex: {jp: "この店のパンはおいしいです。",kana: "このみせのパンはおいしいです。",en: "The bread at this shop is delicious.",zh: "这家店的面包很好吃。"}},
  {word: "会社",kana: "かいしゃ",accent: 0,en: "company; office",zh: "公司",ex: {jp: "会社は駅の前にあります。",kana: "かいしゃはえきのまえにあります。",en: "The company is in front of the station.",zh: "公司在车站前面。"}},
  {word: "銀行",kana: "ぎんこう",accent: 0,en: "bank",zh: "银行",ex: {jp: "銀行でお金をおろします。",kana: "ぎんこうでおかねをおろします。",en: "I'll withdraw money at the bank.",zh: "在银行取钱。"}},
  {word: "病院",kana: "びょういん",accent: 0,en: "hospital; clinic",zh: "医院",ex: {jp: "かぜで病院へ行きました。",kana: "かぜでびょういんへいきました。",en: "I went to the hospital because of a cold.",zh: "因为感冒去了医院。"}},
  {word: "図書館",kana: "としょかん",accent: 2,en: "library",zh: "图书馆",ex: {jp: "図書館で本を読みます。",kana: "としょかんでほんをよみます。",en: "I read books at the library.",zh: "在图书馆看书。"}},
  {word: "公園",kana: "こうえん",accent: 0,en: "park",zh: "公园",ex: {jp: "公園で子どもがあそんでいます。",kana: "こうえんでこどもがあそんでいます。",en: "Children are playing in the park.",zh: "孩子们在公园里玩。"}},
  {word: "レストラン",kana: "レストラン",accent: 1,en: "restaurant",zh: "餐厅；饭店",ex: {jp: "あのレストランは高いです。",kana: "あのレストランはたかいです。",en: "That restaurant is expensive.",zh: "那家餐厅很贵。"}},
  {word: "トイレ",kana: "トイレ",accent: 1,en: "toilet; restroom",zh: "厕所；洗手间",ex: {jp: "すみません、トイレはどこですか。",kana: "すみません、トイレはどこですか。",en: "Excuse me, where is the restroom?",zh: "不好意思，洗手间在哪里？"}},
  {word: "部屋",kana: "へや",accent: 2,en: "room",zh: "房间；屋子",ex: {jp: "この部屋はひろいです。",kana: "このへやはひろいです。",en: "This room is spacious.",zh: "这个房间很宽敞。"}},
  {word: "国",kana: "くに",accent: 0,en: "country; home country",zh: "国家；祖国",ex: {jp: "お国はどちらですか。",kana: "おくにはどちらですか。",en: "Which country are you from?",zh: "您是哪国人？"}},
  {word: "町",kana: "まち",accent: 2,en: "town; city",zh: "城镇；街道",ex: {jp: "小さい町にすんでいます。",kana: "ちいさいまちにすんでいます。",en: "I live in a small town.",zh: "我住在一个小镇上。"}},
  {word: "電車",kana: "でんしゃ",accent: 0,en: "train",zh: "电车；列车",ex: {jp: "電車の中で本を読みます。",kana: "でんしゃのなかでほんをよみます。",en: "I read books on the train.",zh: "在电车上看书。"}},
  {word: "車",kana: "くるま",accent: 0,en: "car",zh: "汽车；车",ex: {jp: "父はあたらしい車を買いました。",kana: "ちちはあたらしいくるまをかいました。",en: "My father bought a new car.",zh: "爸爸买了新车。"}},
  {word: "バス",kana: "バス",accent: 1,en: "bus",zh: "公共汽车；巴士",ex: {jp: "バスは十時に来ます。",kana: "バスはじゅうじにきます。",en: "The bus comes at ten o'clock.",zh: "公共汽车十点来。"}},
  {word: "自転車",kana: "じてんしゃ",accent: 2,en: "bicycle",zh: "自行车",ex: {jp: "自転車で駅まで行きます。",kana: "じてんしゃでえきまでいきます。",en: "I ride my bicycle to the station.",zh: "骑自行车去车站。"}},
  {word: "タクシー",kana: "タクシー",accent: 1,en: "taxi",zh: "出租车",ex: {jp: "駅からタクシーにのりました。",kana: "えきからタクシーにのりました。",en: "I took a taxi from the station.",zh: "从车站坐了出租车。"}},
  {word: "天気",kana: "てんき",accent: 1,en: "weather; fine weather",zh: "天气；好天气",ex: {jp: "今日はいい天気ですね。",kana: "きょうはいいてんきですね。",en: "It's nice weather today, isn't it?",zh: "今天天气真好啊。"}},
  {word: "雨",kana: "あめ",accent: 1,en: "rain",zh: "雨",ex: {jp: "雨がふっています。",kana: "あめがふっています。",en: "It's raining.",zh: "正在下雨。"}},
  {word: "雪",kana: "ゆき",accent: 2,en: "snow",zh: "雪",ex: {jp: "山に雪がふりました。",kana: "やまにゆきがふりました。",en: "Snow fell on the mountains.",zh: "山上下雪了。"}},
  {word: "山",kana: "やま",accent: 2,en: "mountain",zh: "山",ex: {jp: "あの山はとても高いです。",kana: "あのやまはとてもたかいです。",en: "That mountain is very high.",zh: "那座山很高。"}},
  {word: "川",kana: "かわ",accent: 2,en: "river",zh: "河；河流",ex: {jp: "川に魚がいます。",kana: "かわにさかながいます。",en: "There are fish in the river.",zh: "河里有鱼。"}},
  {word: "海",kana: "うみ",accent: 1,en: "sea; ocean",zh: "海；大海",ex: {jp: "先週、海へ行きました。",kana: "せんしゅう、うみへいきました。",en: "I went to the sea last week.",zh: "上周去了海边。"}},
  {word: "空",kana: "そら",accent: 1,en: "sky",zh: "天空",ex: {jp: "今日は空があおいです。",kana: "きょうはそらがあおいです。",en: "The sky is blue today.",zh: "今天天空很蓝。"}},
  {word: "ごはん",kana: "ごはん",accent: 1,en: "cooked rice; meal",zh: "米饭；饭",ex: {jp: "毎日ごはんを食べます。",kana: "まいにちごはんをたべます。",en: "I eat rice every day.",zh: "我每天吃米饭。"}},
  {word: "パン",kana: "パン",accent: 1,en: "bread",zh: "面包",ex: {jp: "朝、パンを食べます。",kana: "あさ、パンをたべます。",en: "I eat bread in the morning.",zh: "早上吃面包。"}},
  {word: "肉",kana: "にく",accent: 2,en: "meat",zh: "肉",ex: {jp: "肉が好きです。",kana: "にくがすきです。",en: "I like meat.",zh: "我喜欢吃肉。"}},
  {word: "魚",kana: "さかな",accent: 0,en: "fish",zh: "鱼",ex: {jp: "魚を食べますか。",kana: "さかなをたべますか。",en: "Do you eat fish?",zh: "你吃鱼吗？"}},
  {word: "野菜",kana: "やさい",accent: 0,en: "vegetables",zh: "蔬菜",ex: {jp: "店で野菜を買います。",kana: "みせでやさいをかいます。",en: "I buy vegetables at the shop.",zh: "我在店里买蔬菜。"}},
  {word: "水",kana: "みず",accent: 0,en: "water (cold)",zh: "水（一般指凉水）",ex: {jp: "水をください。",kana: "みずをください。",en: "Water, please.",zh: "请给我水。"}},
  {word: "お茶",kana: "おちゃ",accent: 0,en: "tea (green tea)",zh: "茶（通常指绿茶）",ex: {jp: "お茶を飲みませんか。",kana: "おちゃをのみませんか。",en: "Would you like to drink some tea?",zh: "要不要喝点茶？"}},
  {word: "コーヒー",kana: "コーヒー",accent: 3,en: "coffee",zh: "咖啡",ex: {jp: "朝はコーヒーを飲みます。",kana: "あさはコーヒーをのみます。",en: "I drink coffee in the morning.",zh: "我早上喝咖啡。"}},
  {word: "牛乳",kana: "ぎゅうにゅう",accent: 0,en: "milk",zh: "牛奶",ex: {jp: "牛乳を一本買いました。",kana: "ぎゅうにゅうをいっぽんかいました。",en: "I bought a bottle of milk.",zh: "我买了一瓶牛奶。"}},
  {word: "たまご",kana: "たまご",accent: null,en: "egg",zh: "鸡蛋；蛋",ex: {jp: "たまごを二つ食べました。",kana: "たまごをふたつたべました。",en: "I ate two eggs.",zh: "我吃了两个鸡蛋。"}},
  {word: "くだもの",kana: "くだもの",accent: 2,en: "fruit",zh: "水果",ex: {jp: "くだものが好きです。",kana: "くだものがすきです。",en: "I like fruit.",zh: "我喜欢水果。"}},
  {word: "りんご",kana: "りんご",accent: 0,en: "apple",zh: "苹果",ex: {jp: "りんごを一つください。",kana: "りんごをひとつください。",en: "One apple, please.",zh: "请给我一个苹果。"}},
  {word: "おかし",kana: "おかし",accent: 2,en: "sweets; snacks",zh: "点心；零食",ex: {jp: "子どもはおかしが好きです。",kana: "こどもはおかしがすきです。",en: "Children like sweets.",zh: "孩子们喜欢零食。"}},
  {word: "朝ごはん",kana: "あさごはん",accent: 3,en: "breakfast",zh: "早饭",ex: {jp: "七時に朝ごはんを食べます。",kana: "しちじにあさごはんをたべます。",en: "I eat breakfast at seven.",zh: "我七点吃早饭。"}},
  {word: "昼ごはん",kana: "ひるごはん",accent: 3,en: "lunch",zh: "午饭",ex: {jp: "昼ごはんはすしです。",kana: "ひるごはんはすしです。",en: "Lunch is sushi.",zh: "午饭是寿司。"}},
  {word: "晩ごはん",kana: "ばんごはん",accent: 3,en: "dinner",zh: "晚饭",ex: {jp: "母と晩ごはんを作ります。",kana: "ははとばんごはんをつくります。",en: "I make dinner with my mother.",zh: "我和妈妈一起做晚饭。"}},
  {word: "ラーメン",kana: "ラーメン",accent: 1,en: "ramen (noodle soup)",zh: "拉面",ex: {jp: "この店のラーメンはおいしいです。",kana: "このみせのラーメンはおいしいです。",en: "This shop's ramen is delicious.",zh: "这家店的拉面很好吃。"}},
  {word: "すし",kana: "すし",accent: null,en: "sushi",zh: "寿司",ex: {jp: "すしを食べたいです。",kana: "すしをたべたいです。",en: "I want to eat sushi.",zh: "我想吃寿司。"}},
  {word: "本",kana: "ほん",accent: 1,en: "book",zh: "书",ex: {jp: "夜、本を読みます。",kana: "よる、ほんをよみます。",en: "I read books at night.",zh: "我晚上看书。"}},
  {word: "ノート",kana: "ノート",accent: 1,en: "notebook",zh: "笔记本",ex: {jp: "ノートに名前を書いてください。",kana: "ノートになまえをかいてください。",en: "Please write your name in the notebook.",zh: "请在笔记本上写名字。"}},
  {word: "えんぴつ",kana: "えんぴつ",accent: 0,en: "pencil",zh: "铅笔",ex: {jp: "えんぴつはどこですか。",kana: "えんぴつはどこですか。",en: "Where is the pencil?",zh: "铅笔在哪里？"}},
  {word: "かばん",kana: "かばん",accent: 0,en: "bag",zh: "包；书包",ex: {jp: "かばんの中に本があります。",kana: "かばんのなかにほんがあります。",en: "There is a book in the bag.",zh: "包里有书。"}},
  {word: "かさ",kana: "かさ",accent: 1,en: "umbrella",zh: "伞",ex: {jp: "雨ですから、かさを持っていきます。",kana: "あめですから、かさをもっていきます。",en: "It's raining, so I'll take an umbrella.",zh: "下雨了，所以我带伞去。"}},
  {word: "時計",kana: "とけい",accent: 0,en: "clock; watch",zh: "钟；表",ex: {jp: "この時計は高いです。",kana: "このとけいはたかいです。",en: "This watch is expensive.",zh: "这块表很贵。"}},
  {word: "電話",kana: "でんわ",accent: 0,en: "telephone; phone call",zh: "电话",ex: {jp: "友だちに電話をします。",kana: "ともだちにでんわをします。",en: "I call my friend.",zh: "我给朋友打电话。"}},
  {word: "テレビ",kana: "テレビ",accent: 1,en: "television",zh: "电视",ex: {jp: "夜、テレビを見ます。",kana: "よる、テレビをみます。",en: "I watch TV at night.",zh: "我晚上看电视。"}},
  {word: "写真",kana: "しゃしん",accent: 0,en: "photograph",zh: "照片",ex: {jp: "ここで写真をとりましょう。",kana: "ここでしゃしんをとりましょう。",en: "Let's take a photo here.",zh: "我们在这里拍张照吧。"}},
  {word: "お金",kana: "おかね",accent: 0,en: "money",zh: "钱（不是“金子”）",ex: {jp: "お金がありません。",kana: "おかねがありません。",en: "I don't have any money.",zh: "我没有钱。"}},
  {word: "くつ",kana: "くつ",accent: 2,en: "shoes",zh: "鞋",ex: {jp: "新しいくつを買いました。",kana: "あたらしいくつをかいました。",en: "I bought new shoes.",zh: "我买了新鞋。"}},
  {word: "服",kana: "ふく",accent: 2,en: "clothes",zh: "衣服",ex: {jp: "この服はきれいですね。",kana: "このふくはきれいですね。",en: "These clothes are pretty, aren't they?",zh: "这件衣服真漂亮啊。"}},
  {word: "新聞",kana: "しんぶん",accent: 0,en: "newspaper",zh: "报纸（不是“新闻”）",ex: {jp: "父は毎朝新聞を読みます。",kana: "ちちはまいあさしんぶんをよみます。",en: "My father reads the newspaper every morning.",zh: "我爸爸每天早上看报纸。"}},
  {word: "手紙",kana: "てがみ",accent: 0,en: "letter (mail)",zh: "信（不是“手纸”）",ex: {jp: "母に手紙を書きます。",kana: "ははにてがみをかきます。",en: "I write a letter to my mother.",zh: "我给妈妈写信。"}},
  {word: "かぎ",kana: "かぎ",accent: 2,en: "key; lock",zh: "钥匙；锁",ex: {jp: "かぎはどこにありますか。",kana: "かぎはどこにありますか。",en: "Where is the key?",zh: "钥匙在哪里？"}},
  {word: "つくえ",kana: "つくえ",accent: 0,en: "desk",zh: "书桌；桌子",ex: {jp: "つくえの上にノートがあります。",kana: "つくえのうえにノートがあります。",en: "There is a notebook on the desk.",zh: "书桌上有笔记本。"}},
  {word: "いす",kana: "いす",accent: 0,en: "chair",zh: "椅子",ex: {jp: "このいすにすわってください。",kana: "このいすにすわってください。",en: "Please sit on this chair.",zh: "请坐这把椅子。"}},
  {word: "頭",kana: "あたま",accent: 3,en: "head",zh: "头",ex: {jp: "頭がいたいです。",kana: "あたまがいたいです。",en: "I have a headache.",zh: "我头疼。"}},
  {word: "目",kana: "め",accent: 1,en: "eye",zh: "眼睛",ex: {jp: "ねこの目は大きいです。",kana: "ねこのめはおおきいです。",en: "Cats' eyes are big.",zh: "猫的眼睛很大。"}},
  {word: "耳",kana: "みみ",accent: 2,en: "ear",zh: "耳朵",ex: {jp: "うさぎの耳は長いです。",kana: "うさぎのみみはながいです。",en: "Rabbits' ears are long.",zh: "兔子的耳朵很长。"}},
  {word: "口",kana: "くち",accent: 0,en: "mouth",zh: "嘴",ex: {jp: "口を大きくあけてください。",kana: "くちをおおきくあけてください。",en: "Please open your mouth wide.",zh: "请把嘴张大。"}},
  {word: "手",kana: "て",accent: 1,en: "hand",zh: "手",ex: {jp: "食べる前に手をあらいます。",kana: "たべるまえにてをあらいます。",en: "I wash my hands before eating.",zh: "吃饭前洗手。"}},
  {word: "足",kana: "あし",accent: 2,en: "foot; leg",zh: "脚；腿",ex: {jp: "足がいたいです。",kana: "あしがいたいです。",en: "My leg hurts.",zh: "我腿疼。"}},
  {word: "おなか",kana: "おなか",accent: 0,en: "stomach; belly",zh: "肚子",ex: {jp: "おなかがすきました。",kana: "おなかがすきました。",en: "I'm hungry.",zh: "我饿了。"}},
  {word: "日本語",kana: "にほんご",accent: 0,en: "Japanese (language)",zh: "日语",ex: {jp: "日本語を勉強しています。",kana: "にほんごをべんきょうしています。",en: "I am studying Japanese.",zh: "我在学日语。"}},
  {word: "英語",kana: "えいご",accent: 0,en: "English (language)",zh: "英语",ex: {jp: "英語は少し分かります。",kana: "えいごはすこしわかります。",en: "I understand a little English.",zh: "我懂一点英语。"}},
  {word: "中国語",kana: "ちゅうごくご",accent: 0,en: "Chinese (language)",zh: "汉语；中文",ex: {jp: "わたしは中国語を話します。",kana: "わたしはちゅうごくごをはなします。",en: "I speak Chinese.",zh: "我说中文。"}},
  {word: "勉強",kana: "べんきょう",accent: 0,en: "study",zh: "学习（不是“勉强”）",ex: {jp: "毎晩二時間勉強します。",kana: "まいばんにじかんべんきょうします。",en: "I study for two hours every evening.",zh: "我每天晚上学习两个小时。"}},
  {word: "宿題",kana: "しゅくだい",accent: 0,en: "homework",zh: "作业",ex: {jp: "今から宿題をします。",kana: "いまからしゅくだいをします。",en: "I'm going to do my homework now.",zh: "我现在开始做作业。"}},
  {word: "仕事",kana: "しごと",accent: 0,en: "work; job",zh: "工作",ex: {jp: "父は会社で仕事をしています。",kana: "ちちはかいしゃでしごとをしています。",en: "My father works at a company.",zh: "我爸爸在公司工作。"}},
  {word: "しけん",kana: "しけん",accent: 2,en: "exam; test",zh: "考试",ex: {jp: "明日しけんがあります。",kana: "あしたしけんがあります。",en: "There is an exam tomorrow.",zh: "明天有考试。"}},
  {word: "クラス",kana: "クラス",accent: 1,en: "class",zh: "班；班级",ex: {jp: "クラスに学生が二十人います。",kana: "クラスにがくせいがにじゅうにんいます。",en: "There are twenty students in the class.",zh: "班里有二十个学生。"}},
  {word: "大きい",kana: "おおきい",accent: 3,en: "big",zh: "大",ex: {jp: "大きい家ですね。",kana: "おおきいいえですね。",en: "What a big house.",zh: "好大的房子啊。"}},
  {word: "小さい",kana: "ちいさい",accent: 3,en: "small",zh: "小",ex: {jp: "小さいかばんを買いました。",kana: "ちいさいかばんをかいました。",en: "I bought a small bag.",zh: "我买了一个小包。"}},
  {word: "新しい",kana: "あたらしい",accent: 4,en: "new",zh: "新",ex: {jp: "これは新しい車です。",kana: "これはあたらしいくるまです。",en: "This is a new car.",zh: "这是新车。"}},
  {word: "古い",kana: "ふるい",accent: 2,en: "old (things, not people)",zh: "旧；老（指物，不指人）",ex: {jp: "この本は古いです。",kana: "このほんはふるいです。",en: "This book is old.",zh: "这本书很旧。"}},
  {word: "高い",kana: "たかい",accent: 2,en: "tall; high; expensive",zh: "高；贵",ex: {jp: "あの山は高いです。",kana: "あのやまはたかいです。",en: "That mountain is high.",zh: "那座山很高。"}},
  {word: "安い",kana: "やすい",accent: 2,en: "cheap",zh: "便宜",ex: {jp: "この店は安いです。",kana: "このみせはやすいです。",en: "This shop is cheap.",zh: "这家店很便宜。"}},
  {word: "長い",kana: "ながい",accent: 2,en: "long",zh: "长",ex: {jp: "長い手紙を書きました。",kana: "ながいてがみをかきました。",en: "I wrote a long letter.",zh: "我写了一封很长的信。"}},
  {word: "短い",kana: "みじかい",accent: 3,en: "short",zh: "短",ex: {jp: "この休みは短いです。",kana: "このやすみはみじかいです。",en: "This holiday is short.",zh: "这个假期很短。"}},
  {word: "暑い",kana: "あつい",accent: 2,en: "hot (weather)",zh: "热（天气）",ex: {jp: "今日はとても暑いです。",kana: "きょうはとてもあついです。",en: "It's very hot today.",zh: "今天非常热。"}},
  {word: "寒い",kana: "さむい",accent: 2,en: "cold (weather)",zh: "冷（天气）",ex: {jp: "今朝は寒いですね。",kana: "けさはさむいですね。",en: "It's cold this morning, isn't it?",zh: "今天早上真冷啊。"}},
  {word: "おいしい",kana: "おいしい",accent: 0,en: "delicious",zh: "好吃；好喝",ex: {jp: "このケーキはおいしいです。",kana: "このケーキはおいしいです。",en: "This cake is delicious.",zh: "这个蛋糕很好吃。"}},
  {word: "たのしい",kana: "たのしい",accent: 3,en: "fun; enjoyable",zh: "开心；愉快",ex: {jp: "日本語の勉強はたのしいです。",kana: "にほんごのべんきょうはたのしいです。",en: "Studying Japanese is fun.",zh: "学日语很开心。"}},
  {word: "いそがしい",kana: "いそがしい",accent: 4,en: "busy",zh: "忙",ex: {jp: "今週はいそがしいです。",kana: "こんしゅうはいそがしいです。",en: "I'm busy this week.",zh: "这周很忙。"}},
  {word: "おもしろい",kana: "おもしろい",accent: 4,en: "interesting; funny",zh: "有趣；好笑",ex: {jp: "この本はおもしろいです。",kana: "このほんはおもしろいです。",en: "This book is interesting.",zh: "这本书很有意思。"}},
  {word: "多い",kana: "おおい",accent: 1,en: "many; a lot",zh: "多",ex: {jp: "東京は人が多いです。",kana: "とうきょうはひとがおおいです。",en: "Tokyo has a lot of people.",zh: "东京人很多。"}},
  {word: "少ない",kana: "すくない",accent: 3,en: "few; little",zh: "少",ex: {jp: "今日は学生が少ないです。",kana: "きょうはがくせいがすくないです。",en: "There are few students today.",zh: "今天学生很少。"}},
  {word: "いい",kana: "いい",accent: 1,en: "good",zh: "好",ex: {jp: "今日はいい天気ですね。",kana: "きょうはいいてんきですね。",en: "Nice weather today, isn't it?",zh: "今天天气真好啊。"}},
  {word: "好き",kana: "すき",accent: 2,en: "liked; to like (な-adjective)",zh: "喜欢",ex: {jp: "わたしはねこが好きです。",kana: "わたしはねこがすきです。",en: "I like cats.",zh: "我喜欢猫。"}},
  {word: "きらい",kana: "きらい",accent: 0,en: "disliked; to dislike (な-adjective)",zh: "讨厌；不喜欢",ex: {jp: "やさいがきらいです。",kana: "やさいがきらいです。",en: "I don't like vegetables.",zh: "我不喜欢蔬菜。"}},
  {word: "元気",kana: "げんき",accent: 1,en: "healthy; energetic; well",zh: "精神；健康",ex: {jp: "お元気ですか。",kana: "おげんきですか。",en: "How are you?",zh: "你好吗？"}},
  {word: "しずか",kana: "しずか",accent: 1,en: "quiet",zh: "安静",ex: {jp: "ここはしずかですね。",kana: "ここはしずかですね。",en: "It's quiet here, isn't it?",zh: "这里真安静啊。"}},
  {word: "きれい",kana: "きれい",accent: 1,en: "pretty; clean",zh: "漂亮；干净",ex: {jp: "この花はきれいです。",kana: "このはなはきれいです。",en: "This flower is pretty.",zh: "这朵花很漂亮。"}},
  {word: "上手",kana: "じょうず",accent: 3,en: "good at; skilful",zh: "擅长；（做得）好（不是“上手”）",ex: {jp: "リンさんは日本語が上手です。",kana: "リンさんはにほんごがじょうずです。",en: "Lin is good at Japanese.",zh: "林日语说得很好。"}},
  {word: "下手",kana: "へた",accent: 2,en: "bad at; unskilful",zh: "不擅长；（做得）差",ex: {jp: "わたしはテニスが下手です。",kana: "わたしはテニスがへたです。",en: "I'm bad at tennis.",zh: "我网球打得不好。"}},
  {word: "ひま",kana: "ひま",accent: 0,en: "free (time); not busy",zh: "有空；闲",ex: {jp: "明日はひまですか。",kana: "あしたはひまですか。",en: "Are you free tomorrow?",zh: "你明天有空吗？"}},
  {word: "大丈夫",kana: "だいじょうぶ",accent: 3,en: "all right; OK",zh: "没关系；没问题",ex: {jp: "大丈夫ですか。",kana: "だいじょうぶですか。",en: "Are you all right?",zh: "你没事吧？"}},
  {word: "行く",kana: "いく",accent: 0,en: "to go",zh: "去",ex: {jp: "明日、学校へ行きます。",kana: "あした、がっこうへいきます。",en: "I'll go to school tomorrow.",zh: "我明天去学校。"}},
  {word: "来る",kana: "くる",accent: 1,en: "to come",zh: "来",ex: {jp: "友だちが家に来ます。",kana: "ともだちがいえにきます。",en: "A friend is coming to my house.",zh: "朋友要来我家。"}},
  {word: "帰る",kana: "かえる",accent: 1,en: "to go home; to return",zh: "回家；回去",ex: {jp: "六時に家へ帰ります。",kana: "ろくじにいえへかえります。",en: "I go home at six.",zh: "我六点回家。"}},
  {word: "する",kana: "する",accent: 0,en: "to do",zh: "做；干",ex: {jp: "毎日テニスをします。",kana: "まいにちテニスをします。",en: "I play tennis every day.",zh: "我每天打网球。"}},
  {word: "食べる",kana: "たべる",accent: 2,en: "to eat",zh: "吃",ex: {jp: "何を食べますか。",kana: "なにをたべますか。",en: "What will you eat?",zh: "你吃什么？"}},
  {word: "飲む",kana: "のむ",accent: 1,en: "to drink",zh: "喝",ex: {jp: "毎朝牛乳を飲みます。",kana: "まいあさぎゅうにゅうをのみます。",en: "I drink milk every morning.",zh: "我每天早上喝牛奶。"}},
  {word: "見る",kana: "みる",accent: 1,en: "to see; to watch",zh: "看",ex: {jp: "友だちとテレビを見ます。",kana: "ともだちとテレビをみます。",en: "I watch TV with a friend.",zh: "我和朋友一起看电视。"}},
  {word: "聞く",kana: "きく",accent: 0,en: "to listen; to ask",zh: "听；问",ex: {jp: "先生に聞きましょう。",kana: "せんせいにききましょう。",en: "Let's ask the teacher.",zh: "我们问问老师吧。"}},
  {word: "読む",kana: "よむ",accent: 1,en: "to read",zh: "读；看（书）",ex: {jp: "毎晩本を読みます。",kana: "まいばんほんをよみます。",en: "I read a book every night.",zh: "我每天晚上看书。"}},
  {word: "書く",kana: "かく",accent: 1,en: "to write",zh: "写",ex: {jp: "ここに名前を書いてください。",kana: "ここになまえをかいてください。",en: "Please write your name here.",zh: "请在这里写名字。"}},
  {word: "話す",kana: "はなす",accent: 2,en: "to speak; to talk",zh: "说；谈话",ex: {jp: "母と電話で話します。",kana: "ははとでんわではなします。",en: "I talk with my mother on the phone.",zh: "我和妈妈打电话聊天。"}},
  {word: "買う",kana: "かう",accent: 0,en: "to buy",zh: "买",ex: {jp: "駅でパンを買いました。",kana: "えきでパンをかいました。",en: "I bought bread at the station.",zh: "我在车站买了面包。"}},
  {word: "会う",kana: "あう",accent: 1,en: "to meet",zh: "见面（不是“会”）",ex: {jp: "明日友だちに会います。",kana: "あしたともだちにあいます。",en: "I'll meet a friend tomorrow.",zh: "我明天和朋友见面。"}},
  {word: "待つ",kana: "まつ",accent: 1,en: "to wait",zh: "等",ex: {jp: "駅で待っています。",kana: "えきでまっています。",en: "I'm waiting at the station.",zh: "我在车站等着。"}},
  {word: "起きる",kana: "おきる",accent: 2,en: "to get up; to wake up",zh: "起床；醒来",ex: {jp: "毎朝六時に起きます。",kana: "まいあさろくじにおきます。",en: "I get up at six every morning.",zh: "我每天早上六点起床。"}},
  {word: "寝る",kana: "ねる",accent: 0,en: "to sleep; to go to bed",zh: "睡觉",ex: {jp: "十一時に寝ます。",kana: "じゅういちじにねます。",en: "I go to bed at eleven.",zh: "我十一点睡觉。"}},
  {word: "休む",kana: "やすむ",accent: 2,en: "to rest; to take time off",zh: "休息；请假",ex: {jp: "今日は学校を休みます。",kana: "きょうはがっこうをやすみます。",en: "I'm staying home from school today.",zh: "今天我请假不去上学。"}},
  {word: "入る",kana: "はいる",accent: 1,en: "to enter; to go in",zh: "进；进入",ex: {jp: "部屋に入ってください。",kana: "へやにはいってください。",en: "Please come into the room.",zh: "请进房间。"}},
  {word: "出る",kana: "でる",accent: 1,en: "to go out; to leave",zh: "出去；离开",ex: {jp: "八時に家を出ます。",kana: "はちじにいえをでます。",en: "I leave home at eight.",zh: "我八点出门。"}},
  {word: "分かる",kana: "わかる",accent: 2,en: "to understand",zh: "懂；明白",ex: {jp: "この字が分かりますか。",kana: "このじがわかりますか。",en: "Do you understand this character?",zh: "你认识这个字吗？"}},
  {word: "ある",kana: "ある",accent: 1,en: "to be; to exist (things); to have",zh: "有；在（用于物）",ex: {jp: "駅の前に店があります。",kana: "えきのまえにみせがあります。",en: "There's a shop in front of the station.",zh: "车站前面有一家店。"}},
  {word: "いる",kana: "いる",accent: 0,en: "to be; to exist (people, animals)",zh: "有；在（用于人和动物）",ex: {jp: "家にねこがいます。",kana: "いえにねこがいます。",en: "There's a cat at home.",zh: "家里有一只猫。"}},
  {word: "使う",kana: "つかう",accent: 0,en: "to use",zh: "用；使用",ex: {jp: "このペンを使ってもいいですか。",kana: "このペンをつかってもいいですか。",en: "May I use this pen?",zh: "我可以用这支笔吗？"}},
  {word: "作る",kana: "つくる",accent: 2,en: "to make",zh: "做；制作",ex: {jp: "日曜日にケーキを作ります。",kana: "にちようびにケーキをつくります。",en: "I make a cake on Sundays.",zh: "我星期天做蛋糕。"}},
  {word: "とても",kana: "とても",accent: 0,en: "very",zh: "很；非常",ex: {jp: "このラーメンはとてもおいしいです。",kana: "このラーメンはとてもおいしいです。",en: "This ramen is very tasty.",zh: "这碗拉面非常好吃。"}},
  {word: "すこし",kana: "すこし",accent: 2,en: "a little",zh: "一点；稍微",ex: {jp: "すこし待ってください。",kana: "すこしまってください。",en: "Please wait a moment.",zh: "请稍等一下。"}},
  {word: "よく",kana: "よく",accent: 1,en: "often; well",zh: "经常；好好地",ex: {jp: "父はよくテレビを見ます。",kana: "ちちはよくテレビをみます。",en: "My father often watches TV.",zh: "我爸爸经常看电视。"}},
  {word: "もう",kana: "もう",accent: 1,en: "already; (with a negative) no longer",zh: "已经；（后接否定）不再",ex: {jp: "もう昼ごはんを食べました。",kana: "もうひるごはんをたべました。",en: "I've already had lunch.",zh: "我已经吃过午饭了。"}},
  {word: "まだ",kana: "まだ",accent: 1,en: "still; (with a negative) not yet",zh: "还；（后接否定）还没",ex: {jp: "まだ宿題をしていません。",kana: "まだしゅくだいをしていません。",en: "I haven't done my homework yet.",zh: "我还没做作业。"}},
  {word: "いつも",kana: "いつも",accent: 1,en: "always; usually",zh: "总是；经常",ex: {jp: "いつも七時に起きます。",kana: "いつもしちじにおきます。",en: "I always get up at seven.",zh: "我总是七点起床。"}},
  {word: "何",kana: "なに",accent: 1,en: "what (also read なん)",zh: "什么（也读なん）",ex: {jp: "これは何ですか。",kana: "これはなんですか。",en: "What is this?",zh: "这是什么？"}},
  {word: "だれ",kana: "だれ",accent: 1,en: "who",zh: "谁",ex: {jp: "これはだれのかさですか。",kana: "これはだれのかさですか。",en: "Whose umbrella is this?",zh: "这是谁的伞？"}},
  {word: "どこ",kana: "どこ",accent: 1,en: "where",zh: "哪里",ex: {jp: "トイレはどこですか。",kana: "トイレはどこですか。",en: "Where is the toilet?",zh: "厕所在哪里？"}},
  {word: "いつ",kana: "いつ",accent: 1,en: "when",zh: "什么时候",ex: {jp: "たんじょう日はいつですか。",kana: "たんじょうびはいつですか。",en: "When is your birthday?",zh: "你的生日是什么时候？"}},
  {word: "どう",kana: "どう",accent: 1,en: "how; what about",zh: "怎么样；如何",ex: {jp: "日本の食べ物はどうですか。",kana: "にほんのたべものはどうですか。",en: "How do you like Japanese food?",zh: "日本的食物怎么样？"}},
  {word: "いくら",kana: "いくら",accent: 1,en: "how much (price)",zh: "多少钱",ex: {jp: "このかばんはいくらですか。",kana: "このかばんはいくらですか。",en: "How much is this bag?",zh: "这个包多少钱？"}},
];
